# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest # 运行在 ubuntu 系统环境下
    steps:
      - uses: actions/checkout@v2 # uses 命令允许我们使用别人定义好的 Action，这里是从仓库检出分支
      - uses: actions/setup-node@v2 # 这里是设置 node 版本
        with: # 这里相当于传递给上面指令的参数，告诉他使用 node@20.10.0 这个版本
          node-version: '20.10.0'
      - name: Install Dependencies # name 定义步骤的名称，这个可以在该 Action 运行起来之后，在 Github Actions Tab 下看到
        run: | # `run: |` 的方式，允许我们一次定义多个要执行的命令
          yarn install
          yarn run build
      - name: Push To Pages
        working-directory: ./dist # 指定下面指令运行的目录
        run: |
          git init
          git checkout -b main
          git add -A
          # 这里把下面所有 `<YOUR_NAME>/<YOUR_EMAIL>/<COMMIT_MSG>/<YOUR_TOKEN>` 替换成你自己的就可以了
          git -c user.name='why-pro' -c user.email='1756667609@qq.com' commit -m 'update'
          # 这里需要一个 共开仓库 的 secrets 配置，这里的 secrets 是一个环境变量，可以直接拿过来直接用
          git remote add origin https://${{secrets.why_pro}}@github.com/who-pro/why-prp.git
          git push origin main -f -q

